services:
  db:
    image: postgres:17
    restart: unless-stopped
    mem_limit: 256m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_default
      - bot_net

  app:
    image: ghcr.io/alexeygekkin/todo:latest
    restart: unless-stopped
    mem_limit: 160m
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - todo_default

  bot:
    image: ghcr.io/alexeygekkin/todo:latest
    restart: unless-stopped
    mem_limit: 256m
    env_file:
      - .env
    depends_on:
      - db
    command: ["python", "-m", "app.bot.run"]
    networks:
      bot_net:
        gw_priority: 100

  scheduler:
    image: ghcr.io/alexeygekkin/todo:latest
    restart: unless-stopped
    mem_limit: 256m
    env_file:
      - .env
    depends_on:
      - db
    command: ["python", "-m", "app.scheduler.run"]
    networks:
      todo_default:
      bot_net:
        gw_priority: 100

volumes:
  postgres_data:

networks:
  todo_default:

  bot_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-bot
    ipam:
      config:
        - subnet: 172.20.0.0/24