"""Update ToDo for Telegramm

Revision ID: 14a22e3d59fe
Revises: 599ffca645b2
Create Date: 2026-08-03 16:09:12.378270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

reminder_type_enum = postgresql.ENUM('MORNING', 'DEADLINE', 'BOTH', name='remindertype')

# revision identifiers, used by Alembic.
revision: str = '14a22e3d59fe'
down_revision: Union[str, Sequence[str], None] = '599ffca645b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    reminder_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('todos', sa.Column('completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('todos', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('reminder_type', sa.Enum('MORNING', 'DEADLINE', 'BOTH', name='remindertype'), nullable=True))
    op.drop_column('todos', 'created_at')
    op.drop_column('todos', 'is_done')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('todos', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('todos', 'reminder_type')
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
    reminder_type_enum.drop(op.get_bind(), checkfirst=True)