"""todo update

Revision ID: 79b6816a96e7
Revises: d47389a7e575
Create Date: 2026-08-04 17:47:04.065508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b6816a96e7'
down_revision: Union[str, Sequence[str], None] = 'd47389a7e575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('deadline_time', sa.Time(), nullable=True))
    op.alter_column('todos', 'reminder_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'reminder_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_column('todos', 'deadline_time')
    # ### end Alembic commands ###
