"""add todo index

Revision ID: 9225baf27a08
Revises: 79b6816a96e7
Create Date: 2026-08-07 17:38:57.472680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9225baf27a08'
down_revision: Union[str, Sequence[str], None] = '79b6816a96e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_todos_user_id_id', 'todos', ['user_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_user_id_id', table_name='todos')
    # ### end Alembic commands ###
