"""todo update

Revision ID: d47389a7e575
Revises: 9afbdff993e7
Create Date: 2026-08-04 16:57:09.731690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd47389a7e575'
down_revision: Union[str, Sequence[str], None] = '9afbdff993e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('target_date', sa.Date(), nullable=True))
    op.alter_column('todos', 'reminder_type',
               existing_type=postgresql.ENUM('MORNING', 'DEADLINE', 'BOTH', name='remindertype'),
               type_=sa.Enum('MORNING', 'DEADLINE', 'BOTH', name='remindertype', native_enum=False),
               existing_nullable=True)
    op.drop_column('todos', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('todos', 'reminder_type',
               existing_type=sa.Enum('MORNING', 'DEADLINE', 'BOTH', name='remindertype', native_enum=False),
               type_=postgresql.ENUM('MORNING', 'DEADLINE', 'BOTH', name='remindertype'),
               existing_nullable=True)
    op.drop_column('todos', 'target_date')
    op.drop_column('todos', 'remind_at')
    # ### end Alembic commands ###
